# Generated by Django 5.1.1 on 2024-10-30 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_cart_cartitem_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
